export const data = [
    {
        key: '1',
        mnv: 'abasjdkajfasd',
        name: 'Nguyen Van A',
        sdt: '0123456789',
        loainv: 'Tài Xế',
        thuoctram: 'BD03',
        quanly: 'Không',
        dichvu: 'Giao hàng tiêu chuẩn',
        createdAt: '31/05/2023 17:05:03',
        status: 'Đã kích hoạt'
    },
    {
        key: '2',
        mnv: 'abasjdkajfasd',
        name: 'Nguyen Van B',
        sdt: '0123456789',
        loainv: 'Tài Xế',
        thuoctram: 'BD03',
        quanly: 'Không',
        dichvu: 'Giao hàng tiêu chuẩn',
        createdAt: '31/05/2023 17:05:03',
        status: 'Đã kích hoạt'
    },
    {
        key: '3',
        mnv: 'abasjdkajfasd',
        name: 'Nguyen Van C',
        sdt: '0123456789',
        loainv: 'Tài Xế',
        thuoctram: 'BD03',
        quanly: 'Không',
        dichvu: 'Giao hàng tiêu chuẩn',
        createdAt: '31/05/2023 17:05:03',
        status: 'Đã kích hoạt'
    },
    {
        key: '4',
        mnv: 'abasjdkajfasd',
        name: 'Nguyen Van D',
        sdt: '0123456789',
        loainv: 'Điều phối',
        thuoctram: 'BD03',
        quanly: 'Không',
        dichvu: 'Giao hàng tiêu chuẩn',
        createdAt: '31/05/2023 17:05:03',
        status: 'Đã kích hoạt'
    },
    {
        key: '5',
        mnv: 'abasjdkajfasd',
        name: 'Nguyen Van E',
        sdt: '0123456789',
        loainv: 'Tài Xế',
        thuoctram: 'BD03',
        quanly: 'Không',
        dichvu: 'Giao hàng tiêu chuẩn',
        createdAt: '31/05/2023 17:05:03',
        status: 'Đã kích hoạt'
    },
    {
        key: '6',
        mnv: 'abasjdkajfasd',
        name: 'Nguyen Van F',
        sdt: '0123456789',
        loainv: 'Tài Xế',
        thuoctram: 'BD03',
        quanly: 'Không',
        dichvu: 'Giao hàng tiêu chuẩn',
        createdAt: '31/05/2023 17:05:03',
        status: 'Đã kích hoạt'
    },
    {
        key: '7',
        mnv: 'abasjdkajfasd',
        name: 'Nguyen Van G',
        sdt: '0123456789',
        loainv: 'Tài Xế',
        thuoctram: 'BD03',
        quanly: 'Không',
        dichvu: 'Giao hàng tiêu chuẩn',
        createdAt: '31/05/2023 17:05:03',
        status: 'Đã kích hoạt'
    },
    {
        key: '8',
        mnv: 'abasjdkajfasd',
        name: 'Nguyen Van H',
        sdt: '0123456789',
        loainv: 'Điều phối',
        thuoctram: 'BD03',
        quanly: 'Không',
        dichvu: 'Giao hàng tiêu chuẩn',
        createdAt: '31/05/2023 17:05:03',
        status: 'Đã kích hoạt'
    },
    {
        key: '9',
        mnv: 'abasjdkajfasd',
        name: 'Nguyen Van I',
        sdt: '0123456789',
        loainv: 'Điều phối',
        thuoctram: 'BD03',
        quanly: 'Không',
        dichvu: 'Giao hàng tiêu chuẩn',
        createdAt: '31/05/2023 17:05:03',
        status: 'Đã kích hoạt'
    },
    {
        key: '10',
        mnv: 'abasjdkajfasd',
        name: 'Nguyen Van J',
        sdt: '0123456789',
        loainv: 'Tài Xế',
        thuoctram: 'BD03',
        quanly: 'Không',
        dichvu: 'Giao hàng tiêu chuẩn',
        createdAt: '31/05/2023 17:05:03',
        status: 'Đã kích hoạt'
    },
    {
        key: '11',
        mnv: 'abasjdkajfasd',
        name: 'Nguyen Van K',
        sdt: '0123456789',
        loainv: 'Tài Xế',
        thuoctram: 'BD03',
        quanly: 'Không',
        dichvu: 'Giao hàng tiêu chuẩn',
        createdAt: '31/05/2023 17:05:03',
        status: 'Đã kích hoạt'
    },
    {
        key: '12',
        mnv: 'abasjdkajfasd',
        name: 'Nguyen Van L',
        sdt: '0123456789',
        loainv: 'Tài Xế',
        thuoctram: 'BD03',
        quanly: 'Không',
        dichvu: 'Giao hàng tiêu chuẩn',
        createdAt: '31/05/2023 17:05:03',
        status: 'Đã kích hoạt'
    },
];